name: api_doc
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/api-doc
description: Dart API documentation browser
version: 0.0.1
dependencies:
  unittest: any
  browser: any
  args: any
  logging: any
  web_ui: any
  js: any
  poppy: any
  widget: any
  routing: any
  # TODO(jmesserly): workaround for web_ui not being published yet
  analyzer_experimental: any
