# Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

application: dartlang-api
version: dartdoc-next

runtime: python27
api_version: 1
threadsafe: true

#default_expiration: "2h"

handlers:
- url: /apidocs/static
  static_dir: out/web/static
  
- url: /apidocs/
  static_files: out/web/index.html
  upload: out/web/index.html

- url: /apidocs/docs/.*
  script: scripts.redirector-v2.application

- url: /apidocs
  static_dir: out/web

- url: /.*
  script: scripts.redirector.application